#!/bin/bash
#===============================================================================
# FILE:         functions.sh
#
# USAGE:        Include in other scripts, e.g. source functions.sh
#
# DESCRIPTION:  Defines but does not execute functions that can be used
#               in other scripts.
#===============================================================================

# Treat unset variables as an error when peforming parameter expansion
# Exit immediately on errors
set -o nounset errexit

#-------------------------------------------------------------------------------
# Basic functions
#-------------------------------------------------------------------------------

# Requires:
#   LOG_FILE
log()
{
    # Use msg with prefix to distinguish logs generated by setup scripts
    local msg="log:$@"

    # Write message to screen and log file
    (echo "$msg" 2>&1) | tee -a $LOG_FILE
    return ${PIPESTATUS[0]}
}

# Requires:
#   LOG_FILE
cmd()
{
    # Record command to be executed to the log file
    echo "cmd:$@" >> $LOG_FILE

    # Execute command
    # Redirect stdout and stderr to screen and log file
    (eval "$@" 2>&1) | tee -a $LOG_FILE
    return ${PIPESTATUS[0]}
}

# Terminates the script when provided error code is nonzero
# Usage: err "$?" "$FUNCNAME" "message to be shown and logged"
err()
{
    local error="$1"
    local funcname="$2"
    local msg="$3"

    if [[ "$error" -ne 0 ]]; then
        log "$funcname: $msg: $error"
        log "Aborting!"
        exit 1
    fi
}

uncommentVar()
{
    local var="$1"
    local file="$2"

    cmd "sed -i \"s|^#\(${var}.*\)$|\1|\" ${file}"
}

commentVar()
{
    local var="$1"
    local file="$2"

    cmd "sed -i \"s|^\(${var}.*\)$|#\1|\" ${file}"
}

#-------------------------------------------------------------------------------
# Composite functions
#-------------------------------------------------------------------------------

installPackage()
{
    log "Install package $@..."
    cmd "pacman -S $@ --noconfirm"
    err "$?" "$FUNCNAME" "failed to install package"
    log "Install package $@...done"
}

